### ISSUE TITLE
Form functionality/state machine improvements

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro-rad#10]
The state machine for forms needs to be able to handle full stack interactions that should include:

- [x] Creation of new top-level entities, as well as related things in sub-forms.
- [x] Dependent loads: A dropdown that populates model data on select (cascading dropdowns...select make, then select model)
- [x] Local and Full-stack validation. Is that username in use?
- [x] Debouncing
- [x] Local and full-stack autocomplete. Address completion, completion of existing tags, create new tag (nested form as an autocomplete, where the ID of the sub-form is the value being set on the parent field)...generalization: to-one or to-many from one entity to an (expandable) subset of things that exist in the database (or perhaps the external world). 
- [x] Saving across multiple servers. The attributes of even a single entity may require writes to several stores. Order of writes should be configurable, and perhaps even two-phase commit (should at least be theoretically possible). Test case should be ability to save image to one store and URL to another.

**Comment by pithyless** [comment]
- [ ] Form on cancel should be exiting the state-machine, routing to cancel-route, and fixing app state. (As of version `0.0.1-alpha-1` it's not cleaning up dirty state before routing)

**Comment by awkay** [comment]
autocomplete is partially built. More options will be added as needed.
