### ISSUE TITLE
field-labels not handle as function

### ISSUE THREAD

**Issue by schneiderlin** [fulcrologic/fulcro-rad#129]
https://github.com/fulcrologic/fulcro-rad/blob/1f08ec89e04249b7fba8307c067b6955162828ee/src/main/com/fulcrologic/rad/form.cljc#L1752C1-L1773C18

docstring says
> `::form/field-labels`: A map from attribute keyword to a string or function returning a string.

but 
`(get-in options [::field-labels k])` only handle field-labels as a map

**Comment by awkay** [comment]
Look again.  `?!` is a helper that does just that, and it is present in the code you referenced:

```
...
        field-label (**?!** (or
                          (get-in options [::field-labels k])
                          (::field-label attribute)
                          (ao/label attribute)
                          (some-> k name str/capitalize (str/replace #"-" " "))) form-instance)]
...

**Comment by awkay** [comment]
perhaps you misunderstood...it is:
```
{:k (fn ...)
 :k2 (fn ...)}
```
not `(fn [...] {:k val :k2 val})`

**Comment by schneiderlin** [comment]
thank you for the clarification, I try `:field-labels (constantly "label")` without success, so it should be `:field-labels {:k (constantly "label")}`

**Comment by awkay** [comment]
It does not need to be a function...it can just be a string. Look at what
`?!` does.
