### ISSUE TITLE
load! broken between alpha 12 and 14

### ISSUE THREAD

**Issue by holyjak** [fulcrologic/fulcro-rad#32]
On 0.0.1-alpha-14, `df/load!` logs many Spec errors because of missing `:children` key. When I produce the AST manually, `:children` is there (and there is no `:params nil` contrary to the error below):

```
ERROR  com/fulcrologic/fulcro/algorithms/tx_processing.cljc:413 compute-desired-ast-node's return type
 -- Spec failed --------------------

  {:com.fulcrologic.fulcro.algorithms.tx-processing/results ...,
   :com.fulcrologic.fulcro.algorithms.tx-processing/state-before-action
   ...,
   :com.fulcrologic.fulcro.algorithms.tx-processing/dispatch ...,
   :com.fulcrologic.fulcro.algorithms.tx-processing/started? ...,
   :com.fulcrologic.fulcro.algorithms.tx-processing/original-ast-node
   ...,
   :com.fulcrologic.fulcro.algorithms.tx-processing/complete? ...,
   :com.fulcrologic.fulcro.algorithms.tx-processing/idx ...,
   :com.fulcrologic.fulcro.algorithms.tx-processing/desired-ast-nodes
   ...,
   :com.fulcrologic.fulcro.algorithms.tx-processing/transmitted-ast-nodes
   {:remote
    {:type ..., :children [{:type :join,
                            :dispatch-key :root,
                            :key :root,
                            :query
                            [:ui/parameters
                             :ui/cache
                             :ui/busy?
                             :ui/page-count
                             :ui/current-page
                             {:ui/current-rows [:account/id :account/name :account/active?]}
                             [:ui.fulcro.client.data-fetch.load-markers/by-id _]],
                            :component com.example.ui.account-forms/AccountList,
                            :params nil}], :params ...}}}
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

when conformed as

  {:type :join, :dispatch-key [:prop :root], :key [:prop :root], :query [:query [[:prop :ui/parameters] [:prop :ui/cache] [:prop :ui/busy?] [:prop :ui/page-count] [:prop :ui/current-page] [:join {[:prop :ui/current-rows] [:query [[:prop :account/id] [:prop :account/name] [:prop :account/active?]]]}] [:ident [:ui.fulcro.client.data-fetch.load-markers/by-id _]]]], :component com.example.ui.account-forms/AccountList, :params nil}

should satisfy

  (fn
   [%]
   (if
    (-> % :query first (= :recursion))
    %
    (if (contains? % :children) % false)))
```

## Replication steps

1. Check out fulcro-rad-demo version 5a416c8 (i.e. the latest master as of now, comited on Apr 11th).
2. Log in to the app
3. In the ClojureScript REPL, inside `com.example.ui`, run `(com.fulcrologic.fulcro.data-fetch/load! com.example.client/app :root AccountList)` and check the Browser Console for the ensuing 52 errors logged.

## Additional info

On the previous RAD demo master (03c71d7 - demo release with html5 routing, row actions, report actions, linking, form linking, and more (2 weeks ago), RAD version "0.0.1-alpha-12"), this error does not happen.

Also, when I retrieve the AST manually, it _does_ contain `:children` but does not contain _:params nil_. I haven't been able to replicate this in the demo, though, because when I do

```clojure
;; ns com.example.ui, url http://localhost:3000/accounts?_rp_=WyJeICJd&
(require '[edn-query-language.core :as eql])
(eql/query->ast (comp/get-query MainRouter))
```

then the current route join is `{:com.fulcrologic.fulcro.routing.dynamic-routing/current-route [*]} instead of the expected query of AccountList.

**Comment by awkay** [comment]
Your load call is wrong.  What is broken in the demo???

**Comment by holyjak** [comment]
Why is the load call wrong? Because there is no resolver for `:root`? That is not really the point, it was the simplest way I find to replicate a real problem I discovered in my application, namely Spec error in `compute-desired-ast-nodes`. In my application I have a valid load that worked before I upgraded to the latest demo (and it still seems to work, just logs plenty of these errors).

> What is broken in the demo???

Nothing, the problem is not in the demo but in fulcro-rad itself. The problem is that `load!` of components that include a dynamic router with a report as a target now log the error displayed above, which the did not in the previous version.

I would be more that happy to provide additional troubleshooting information. I though the replication steps above would be enough. Even if the load! is "wrong", it demonstrate the issue (and the lack thereof in RAD alpha 12).

**Comment by awkay** [comment]
sorry, I misread your load. I thought you forgot to pass `app`.  I'll fix spec failures at some pt...in this case, this is an EQL spec error I think, and I don't really care at the moment. If I see it, I'll fix it.

**Comment by holyjak** [comment]
How to work around it? Having 10s of huge errors logged on each render
makes it much more difficult to develop.

**Comment by holyjak** [comment]
FYI I have worked around the problem by adding this to my `com.example.client` (cljs) namespace:

```clojure
;; ns: add `[cljs.spec.alpha :as s]` to :require, then:
(s/def :edn-query-language.ast/node any?)
```

to effectively disable the failing spec. There is certainly a better way but I don't know it :)
