### ISSUE TITLE
Database Adaptor for key-value stores

### ISSUE THREAD

**Issue by chrismurrph** [fulcrologic/fulcro-rad#46]
I've made a start. See the README here:

https://github.com/chrismurrph/mem-kv

That's the RAD Demo working with an atom-based store.

Next step, me to open a PR that will establish `com.fulcrologic.rad.database-adapters.key-value` in fulcrologic...

**Comment by awkay** [comment]
Added repo and sent invite. You should have push permissions on that repo (it has no commits yet)

**Comment by awkay** [comment]
https://github.com/fulcrologic/fulcro-rad-kvstore
