### ISSUE TITLE
Detect and warn when model's resolvers are not used in the parser

### ISSUE THREAD

**Issue by nisley** [fulcrologic/fulcro-rad#50]
After getting the Fulcro RAD Demo running, I decided to practice by adding new models and connecting them. These pieces were similar to Item and Category and I mirrored almost everything about them.

After building up new report lists and forms to view and add these models, everything worked as expected - except the display of the equivalent of the Category in the Item list ([Inventory Report](http://localhost:3000/item-inventory-report)). Frustrated, I dug into the database (datomic) and confirmed the data was getting stored and was identical in structure of categories and items.  

After many, many hours of searching - of thinking I mistyped a keyword, a datomic setup, or pathom query, I finally found my way to the parser. Once I saw the resolvers list I immediately deduced my problem. 

It would be nice for newbies or for the forgetful type if Fulcro RAD could detect and warn that there are model resolvers that are not in the (any?) parser.

To recreate this behavior, simply comment out this line in parser.clj:
`item/resolvers`

**Comment by nisley** [comment]
Reflecting further, I had a similar issue when I did not add one of my new models to the overall model.cljc all-attributes vector.  That was easier to diagnose because at least I had the schema output to fall back on, but it was a roadblock.

Why not designate one or more model folders and everything in there is included in attribute and resolving lists?

**Comment by awkay** [comment]
There is no way to do this without creating a system of side-effects, which means you'd have to make sure to either require them, or resort to some kind of classpath scanning scheme. Nothing is perfect, and they all suffer from some issue or another.

Having it be explicit, as it is designed, is the easiest thing to debug by far. Either it is in the list or not. period. There's no way for me to warn about things you didn't tell me, and I'm not willing to add classpath scanning to the library. Feel free to add your own extension that does so: it is a pretty easy thing to add: just make a macro that wraps `defattr` and puts them in a registry, and then use that registry as your input to the parser.

Then all you have to do is remember to require the namespace in the parser construction.
