### ISSUE TITLE
Fulcro RAD SQL plugin may not work for Postgres

### ISSUE THREAD

**Issue by sittim** [fulcrologic/fulcro-rad#52]
In the RAD SQL plugin, the line

```clojure
          (format "ALTER TABLE %s ADD COLUMN IF NOT EXISTS %s ENUM(%s);\n" table column enums)
```
Which can be see [here](https://github.com/fulcrologic/fulcro-rad-sql/blob/224df4e97624908a8c6f15a4b0ef6016fab3dafd/src/main/com/fulcrologic/rad/database_adapters/sql/migration.clj#L116)

may not work correctly in Postgres.  Unless I am wrong, Postgres requires an explicit creation of enumerated types.  So, as a hack, I replaced the line above with:

```clojure
          (str (format "CREATE TYPE %s_T AS ENUM (%s);\n" column enums)
                 (format "ALTER TABLE %s ADD COLUMN IF NOT EXISTS %s %s_t;\n" table column column))
```

And of course it works but has other consequence for example the string hast be cast with `::type_t` when pushing data.  For example:

```clojure
                 (new-account (new-uuid 100) "Tony" "tony@example.com" "letmein" salt iterations
                   :account/primary_address (new-uuid 300)
                   :account/role ":account.role/superuser".      ; <== NOTICE the role needs ::role_t cast
                   :zone_id ":time-zone.zone-id/America-Los_Angeles")
```

This code is from [here](https://github.com/fulcrologic/fulcro-rad-demo/blob/f840996486fcedfaa3871443ca7499ed3a3cf62a/src/sql/development.clj#L90-L93)

Since this is in plugin that is generic for SQL, should there be a more elegant solution that covers h2 and postgres?  Thoughts?

**Comment by awkay** [comment]
I'm using Postgresql on one of my projects, and yeah, I make schema by hand and avoid enums for exactly that reason because I just don't have time to maintain all the OSS repos. This one was partially a volunteer effort, but no one has really stepped up to work on it, and I really don't have the time.  It needs a *lot* of work to be production-ready IMO, and I'm not going to be the one doing it, sorry.  If you want to step up as a maintainer, I'm totally open to it.

**Comment by sittim** [comment]
Understand.  I gave the idea of taking on this project a lot of thought, and I do not think that I am mature enough in Clojure to take it on, but I will be glad to do some pull requests that are safe enough.

As far as the enums, that makes sense.
