### ISSUE TITLE
Add cypress full-stack tests

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro-rad#9]
Once we get a base example going we should create a set of cypress tests that exercise it, and can be run with a variety of adapters. This could be used to test the full-stack functionality when swapping out things like form generators, database adapters, etc.

**Comment by yannvanhalewyn** [comment]
I've been wanting to try out Cypress, so I'd like to pick this up when the time comes.

**Comment by awkay** [comment]
great, I've got the basics set up in another project...so I could help get you started.

**Comment by awkay** [comment]
not going to happen anytime soon unless someone steps up. Closing for now.
