### ISSUE TITLE
remove-omissions not working

### ISSUE THREAD

**Issue by eoogbe** [fulcrologic/fulcro-rad#98]
`remove-omissions` does not actually remove sensitive keys because of 2 bugs in its implementation.

First, look at what gets passed in:

```
(defn remove-omissions
  [config tx] ; This takes in a config
  (let [sensitive-keys (get-in config [::config :sensitive-keys] #{})]
    ; ...
    ))

(defn- log! [env msg value]
  ; ...
  (pr-str (remove-omissions config value))
  ; ...
  )

(defn log-request! [{:keys [env tx] :as req}]
  (let [config         (:config env)
        sensitive-keys (conj
                         (get-in config [::config :sensitive-keys] #{})
                         :com.wsscode.pathom/trace)]
    (log! env "transaction: " (remove-omissions sensitive-keys tx)) ; This is sending sensitive-keys
    req))

(defn log-response!
  [{:keys [config] :as env} response]
  (let [sensitive-keys (conj
                         (get-in config [::config :sensitive-keys] #{})
                         :com.wsscode.pathom/trace)]
    (log! env "response: " (remove-omissions sensitive-keys response)) ; This is sending sensitive-keys
    response))
```

`log-request!` and `log-response!` are parsing the sensitive keys to send into `remove-omissions` even though `remove-omissions` repeats this actions. That means what reaches `remove-omissions` is `nil`.

The second bug is that the config passed into `new-parser` is never actually put into the env. So `{:keys [config] :as env}` will always get `nil` as the config.

**Comment by awkay** [comment]
To be honest, I'd rather just delete that whole mess than fix it. Be better for the user to just add their own plugin to accomplish it, which is the solution I'd suggest to you.
